### PR TITLE
Fix sum formatter without decimal and whitespace group separator

### PR DESCRIPTION
**Pull request by timbaev**
## Problem №1
The formatter of the sum incorrectly sets the cursor position when deleting numbers if the format have whitespace separator and suffix with 2 characters (one of which is a whitespace). This issue #28 has already been created, but hasn't yet been resolved.

### Solution
The solution to this problem was to uniquely determine the whitespace for the group separator from the whitespace in the suffix. Therefore, the additional function `isGroupingSeparator(_:, in:, at:)` was added which helps to understand whether there is a whitespace for grouping numbers or not.

## Problem №2
The second problem was again in setting the cursor to the wrong position when deleting numbers if the formatter didn't have a decimal separator. In this case, the decimal separator was equal to the group one.

### Solution
The solution is simple - just check that the decimal separator is not equal to the group separator, thereby we can uniquely determine it. In addition to this, to correctly format the sum without a decimal separator with a suffix, it was necessary to update the functions `parseMaximumFractionDigits(format:, decimalSeparator:, suffix:, patternSymbol:)` and `parseGroupingSize(format :, groupingSeparator:, decimalSeparator:, suffix:)`

## Unit tests
To all this, I added tests to make sure that everything works correctly and does not break in the future under changes.

### CODE REVIEW

**Review by RinatMukhammetzyanov — APPROVED** [review]

**Comment by TimurShafigullin** [comment]
@luximetr this framework is supported? 😅

**Comment by timbaev** [comment]
@luximetr this framework is supported? 🙂

**Comment by luximetr** [comment]
Yes, sorry. I will approve ASAP.

**Comment by timbaev** [comment]
@luximetr any updates?

**Comment by luximetr** [comment]
Thank you for your big work, but I found more simple solution of problem 1 (version 2.0.1). About problem 2, do you have problem with this? Do you use it? If not I will leave it till someone will use it.

**Comment by timbaev** [comment]
@luximetr Thank you. Yes we faced with problem №2 in our project.

**Comment by luximetr** [comment]
Okay, will fix it.

**Comment by luximetr** [comment]
> @luximetr Thank you. Yes we faced with problem №2 in our project.

@timbaev
Do you mean format like this "####,## $"? If yes, this is looks ambiguous, I can not know what "," symbol should be (decimal or group separator). So this format as string I am using for parse all components of formatter and pass it to number formatter. Instead you can try use ```SumTextInputFormatter(numberFormatter: numberFormatter)```.
For format "####,## $" if "," is a decimal separator you can create number formatter like this
```
let numberFormatter = NumberFormatter()
    numberFormatter.allowsFloats = true
    numberFormatter.groupingSeparator = ""
    numberFormatter.decimalSeparator = ","
    numberFormatter.positiveSuffix = " $"
    numberFormatter.maximumFractionDigits = 2
```
Let me know if it helped, because I don't know how to parse such format.

**Comment by timbaev** [comment]
@luximetr In our case we faced with format like this: `# ### $` (I think whitespace `" "` also is ambiguous). Ok, we will try using `SumTextInputFormatter(numberFormatter:)`, thank you for you help!

**Pull request closed without merging**
