### PR TITLE
Send `.editingChanged` action when formatting text in `UITextField`

### PR DESCRIPTION
**Pull request by ky1vstar**
Since `UITextField` is a `UIControl` subclass, it sends different control actions during its life-cycle. One of that action is `.editingChanged` when delegate's `textField(_:shouldChangeCharactersIn:replacementString:)` returns `true`. If you look at `RxCocoa`'s `UITextField` wrapper implementation [here](https://github.com/ReactiveX/RxSwift/blob/1a1fa37b0d08e0f99ffa41f98f340e8bc60c35c4/RxCocoa/iOS/UITextField%2BRx.swift#L22) and [here](https://github.com/ReactiveX/RxSwift/blob/1a1fa37b0d08e0f99ffa41f98f340e8bc60c35c4/RxCocoa/iOS/UIControl%2BRx.swift#L73) you will see that it depends on this mechanism. So this PR adds actions emitting when we formatting text in `UITextField`.

### CODE REVIEW

**Comment by luximetr** [comment]
> Since `UITextField` is a `UIControl` subclass, it sends different control actions during its life-cycle. One of that action is `.editingChanged` when delegate's `textField(_:shouldChangeCharactersIn:replacementString:)` returns `true`. If you look at `RxCocoa`'s `UITextField` wrapper implementation [here](https://github.com/ReactiveX/RxSwift/blob/1a1fa37b0d08e0f99ffa41f98f340e8bc60c35c4/RxCocoa/iOS/UITextField%2BRx.swift#L22) and [here](https://github.com/ReactiveX/RxSwift/blob/1a1fa37b0d08e0f99ffa41f98f340e8bc60c35c4/RxCocoa/iOS/UIControl%2BRx.swift#L73) you will see that it depends on this mechanism. So this PR adds actions emitting when we formatting text in `UITextField`.

So, will RxCocoa work with your changes?

**Comment by ky1vstar** [comment]
Yes, it will. Everyone who uses events for listening `UITextField` text changes will profit.

**Comment by ky1vstar** [comment]
The same is applicable for observing text changes using `NotificationCenter`.

**Comment by luximetr** [comment]
Merged. Available from version 2.5.1.

**Pull request merged**
